import {
  userSchema,
  channelSchema,
  subScribeSchema,
  videoSchema,
  likeSchema,
  commentSchema,
  subCommentSchema,
} from './schema/';
import {
  userResolver,
  ChannelResolver,
  subscribeResolver,
  VideoResolver,
  likeResolver,
  commentResolver,
  subCommentResolver,
} from './resolver';
import { mergeResolvers, mergeTypeDefs } from '@graphql-tools/merge';
import {
  AuthMiddleware,
  loginValidateMiddleware,
  signupValidateMiddleware,
  verifyEmailValidateMiddleware,
  resendCodeOnEmailValidateMiddleware,
  verifyOtpValidateMiddleware,
  imageValidation,
  checkAuthMiddleware,
  videoValidation,
  verifiedChannelByAdminValidateMiddleware,
  videoDeleteValidateMiddleware,
  videoUpdateValidateMiddleware,
  createLikeOnVideoValidateMiddleware,
  createCommentOnVideoValidateMiddleware,
  deleteCommentOnVideoValidateMiddleware,
  updateCommentOnVideoValidateMiddleware,
  updateSubCommentOnVideoValidateMiddleware,
  deleteSubCommentOnVideoValidateMiddleware,
} from './directives/';
const typedef = mergeTypeDefs([
  userSchema,
  channelSchema,
  subScribeSchema,
  videoSchema,
  likeSchema,
  commentSchema,
  subCommentSchema,
]);
const resolvers = mergeResolvers([
  userResolver,
  ChannelResolver,
  subscribeResolver,
  VideoResolver,
  likeResolver,
  commentResolver,
  subCommentResolver,
]);
export {
  resolvers,
  typedef,
  AuthMiddleware,
  loginValidateMiddleware,
  signupValidateMiddleware,
  verifyEmailValidateMiddleware,
  resendCodeOnEmailValidateMiddleware,
  verifyOtpValidateMiddleware,
  imageValidation,
  checkAuthMiddleware,
  videoValidation,
  verifiedChannelByAdminValidateMiddleware,
  videoDeleteValidateMiddleware,
  videoUpdateValidateMiddleware,
  createLikeOnVideoValidateMiddleware,
  createCommentOnVideoValidateMiddleware,
  deleteCommentOnVideoValidateMiddleware,
  updateCommentOnVideoValidateMiddleware,
  updateSubCommentOnVideoValidateMiddleware,
  deleteSubCommentOnVideoValidateMiddleware,
};
